name: modal_bottom_sheet
description: "Create awesome and powerful modal bottom sheets. Material, Cupertino iOS 13 or create your own style"
version: 2.1.2+1
homepage: "https://github.com/jamesblasco/modal_bottom_sheet"

environment:
  flutter: ">=3.7.0"
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0
